DEF FIRST_FONT_TILE EQU 8

charmap " ", 0
charmap "𐑐", FIRST_FONT_TILE + 0
charmap "𐑑", FIRST_FONT_TILE + 1
charmap "𐑒", FIRST_FONT_TILE + 2
charmap "𐑓", FIRST_FONT_TILE + 3
charmap "𐑔", FIRST_FONT_TILE + 4
charmap "𐑕", FIRST_FONT_TILE + 5
charmap "𐑖", FIRST_FONT_TILE + 6
charmap "𐑗", FIRST_FONT_TILE + 7
charmap "𐑘", FIRST_FONT_TILE + 8
charmap "𐑙", FIRST_FONT_TILE + 9
charmap "𐑚", FIRST_FONT_TILE + 10
charmap "𐑛", FIRST_FONT_TILE + 11
charmap "𐑜", FIRST_FONT_TILE + 12
charmap "𐑝", FIRST_FONT_TILE + 13
charmap "𐑞", FIRST_FONT_TILE + 14
charmap "𐑟", FIRST_FONT_TILE + 15
charmap "𐑠", FIRST_FONT_TILE + 16
charmap "𐑡", FIRST_FONT_TILE + 17
charmap "𐑢", FIRST_FONT_TILE + 18
charmap "𐑣", FIRST_FONT_TILE + 19
charmap "𐑤", FIRST_FONT_TILE + 20
charmap "𐑥", FIRST_FONT_TILE + 21
charmap "𐑦", FIRST_FONT_TILE + 22
charmap "𐑧", FIRST_FONT_TILE + 23
charmap "𐑨", FIRST_FONT_TILE + 24
charmap "𐑩", FIRST_FONT_TILE + 25
charmap "𐑪", FIRST_FONT_TILE + 26
charmap "𐑫", FIRST_FONT_TILE + 27
charmap "𐑬", FIRST_FONT_TILE + 28
charmap "𐑭", FIRST_FONT_TILE + 29
charmap "𐑮", FIRST_FONT_TILE + 30
charmap "𐑯", FIRST_FONT_TILE + 31
charmap "𐑰", FIRST_FONT_TILE + 32
charmap "𐑱", FIRST_FONT_TILE + 33
charmap "𐑲", FIRST_FONT_TILE + 34
charmap "𐑳", FIRST_FONT_TILE + 35
charmap "𐑴", FIRST_FONT_TILE + 36
charmap "𐑵", FIRST_FONT_TILE + 37
charmap "𐑶", FIRST_FONT_TILE + 38
charmap "𐑷", FIRST_FONT_TILE + 39
charmap "𐑸", FIRST_FONT_TILE + 40
charmap "𐑹", FIRST_FONT_TILE + 41
charmap "𐑺", FIRST_FONT_TILE + 42
charmap "𐑻", FIRST_FONT_TILE + 43
charmap "𐑼", FIRST_FONT_TILE + 44
charmap "𐑽", FIRST_FONT_TILE + 45
charmap "𐑾", FIRST_FONT_TILE + 46
charmap "𐑿", FIRST_FONT_TILE + 47
charmap "0", FIRST_FONT_TILE + 48
charmap "1", FIRST_FONT_TILE + 49
charmap "2", FIRST_FONT_TILE + 50
charmap "3", FIRST_FONT_TILE + 51
charmap "4", FIRST_FONT_TILE + 52
charmap "5", FIRST_FONT_TILE + 53
charmap "6", FIRST_FONT_TILE + 54
charmap "7", FIRST_FONT_TILE + 55
charmap "8", FIRST_FONT_TILE + 56
charmap "9", FIRST_FONT_TILE + 57
charmap ".", FIRST_FONT_TILE + 58
charmap ",", FIRST_FONT_TILE + 59
charmap "-", FIRST_FONT_TILE + 60
charmap "!", FIRST_FONT_TILE + 61
charmap "’", FIRST_FONT_TILE + 62
charmap ":", FIRST_FONT_TILE + 63
